package com.patrisrikanth.learnservlets.tags;

import jakarta.servlet.jsp.JspException;
import jakarta.servlet.jsp.JspWriter;
import jakarta.servlet.jsp.tagext.TagSupport;

public class MyTag extends TagSupport{
	
	public String color;
	
	public void setColor(String color) {
		this.color = color;
	}

	@Override
	public int doStartTag() throws JspException {
		
		try {
			JspWriter out = pageContext.getOut();
			out.println("<p class='text-center' style='color: " + color + "'>This is the html generated by MyTag </p1>");
		} catch(Exception e) {
			e.printStackTrace();
		}
		
		return SKIP_BODY;
	}
}
